apiVersion: v1
kind: Pod
metadata:
  name: service-demo
  labels:
    project: roboshop
    component: frontend
    environment: dev
 # this labels are used to register this pod with services.   
spec:
  containers:
  - name: nginx
    image: nginx    